---
# 图像标注软件的配置文件
image_annotation: 
  # 初始状态下不同系统的缩放系数, 取值在0.5到1.0之间, 如果屏幕分辨率不够大, 可以适当调低
  init_resize:
    windows: 0.5
    macOS: 1.0
  # 是否反转鼠标滚轮的方向
  reverse_mouse_wheel: true
  # 滚轮放大缩小的倍数
  wheel_zoom_factor: [0.8, 1.2]
  # 滚轮放大缩小的最大最小倍数, 最小倍数不能小于1.0
  scale_range: [1.0, 5.0]
  # watch mode下叠加标记的透明度（0-1）
  watch_mode_alpha: 0.25